# Generated by Django 5.0.1 on 2024-06-10 15:02

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default=secrets.token_hex, editable=False, max_length=6),
        ),
    ]
