# Generated by Django 5.0.1 on 2024-06-12 05:15

import BookManager.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookManager', '0002_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default=BookManager.utils.generate_otp, editable=False, max_length=6),
        ),
    ]
