# Generated by Django 5.0.3 on 2024-06-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookManager', '0003_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
