# Generated by Django 5.0.1 on 2024-06-13 12:38

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookManager', '0004_customuser_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', cloudinary.models.CloudinaryField(max_length=255, verbose_name='profile_pic')),
                ('bio', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('books_read', models.ManyToManyField(blank=True, related_name='read_by', to='BookManager.book')),
                ('favorite_books', models.ManyToManyField(blank=True, related_name='favorited_by', to='BookManager.book')),
                ('purchased_books', models.ManyToManyField(blank=True, related_name='purchased_by', to='BookManager.book')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
