# Generated by Django 5.0.1 on 2024-09-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookManager', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='info_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
