# Generated by Django 5.0 on 2025-11-25 09:53

import cloudinary.models
from django.db import migrations, models


def update_google_books_id(apps, schema_editor):
    """Update existing Book records with unique google_books_id values."""
    Book = apps.get_model('BookManager', 'Book')
    for book in Book.objects.filter(google_books_id__isnull=True):
        book.google_books_id = f'temp_{book.id}'
        book.save()
    # Handle any duplicates
    seen = set()
    for book in Book.objects.all().order_by('id'):
        if book.google_books_id in seen:
            book.google_books_id = f'temp_{book.id}'
            book.save()
        seen.add(book.google_books_id)


class Migration(migrations.Migration):

    dependencies = [
        ('BookManager', '0008_add_theme_models'),
    ]

    operations = [
        migrations.RunPython(update_google_books_id, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='purchased_books',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_themes',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_users', to='BookManager.theme'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reading_list',
            field=models.ManyToManyField(blank=True, related_name='on_reading_lists', to='BookManager.book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='google_books_id',
            field=models.CharField(help_text='Google Books volume ID', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='info_link',
            field=models.URLField(blank=True, help_text='Link to Google Books page'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_pic'),
        ),
    ]
